/**
 * @module end-to-end-test
 * End-to-end integration tests validating project creation, document formatting, and live conversion flow.
 */

const { describe, it, before, after } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");

const { createProject, validateAndOpenProject, readProjectDocuments } = require("../src/main/project-service");
const { formatMarkdown, formatCss } = require("../src/main/formatter-service");
const { createConverterService } = require("../src/main/converter-service");

const testLogger = {
  info() {},
  warn() {},
  error() {},
};

describe("End-to-End Workflow Verification", () => {
  let temporaryRootFolder = "";

  before(() => {
    temporaryRootFolder = fs.mkdtempSync(path.join(os.tmpdir(), "atarashii-e2e-"));
  });

  after(() => {
    if (fs.existsSync(temporaryRootFolder)) {
      fs.rmSync(temporaryRootFolder, { recursive: true, force: true });
    }
  });

  it("completes project lifecycle: creation, document editing, formatting, and live conversion", async () => {
    const projectResult = createProject(temporaryRootFolder, "LiveProject", testLogger);
    assert.equal(projectResult.projectName, "LiveProject");

    const projectPath = projectResult.projectPath;
    assert.ok(fs.existsSync(path.join(projectPath, "document.md")));
    assert.ok(fs.existsSync(path.join(projectPath, "style.css")));
    assert.ok(fs.existsSync(path.join(projectPath, "assets")));

    const unformattedMarkdown = "#   Live Title   \n\nThis is sample text.   \n";
    const formattedMarkdown = await formatMarkdown(unformattedMarkdown, testLogger);
    assert.ok(formattedMarkdown.includes("# Live Title"));
    assert.ok(!formattedMarkdown.includes("   \n"));
    fs.writeFileSync(path.join(projectPath, "document.md"), formattedMarkdown, "utf8");

    const unformattedCss = "body{color:#ebede9;margin:0;}";
    const formattedCss = await formatCss(unformattedCss, testLogger);
    assert.ok(formattedCss.includes("color: #ebede9;"));
    fs.writeFileSync(path.join(projectPath, "style.css"), formattedCss, "utf8");

    const documents = readProjectDocuments(projectPath, "document.md", "style.css");
    assert.equal(documents.markdownContent, formattedMarkdown);
    assert.equal(documents.cssContent, formattedCss);

    let capturedLogChunks = "";
    let pdfUpdateDetected = false;

    const converterService = createConverterService(
      testLogger,
      (chunk) => {
        capturedLogChunks += chunk;
      },
      (pdfPath) => {
        if (pdfPath.endsWith("document.pdf")) {
          pdfUpdateDetected = true;
        }
      }
    );

    try {
      await converterService.startLiveConversion(
        projectPath,
        "document.md",
        "style.css",
        "document.pdf"
      );

      const pollStart = Date.now();
      const outputPdfPath = path.join(projectPath, "document.pdf");

      while (Date.now() - pollStart < 15000) {
        if (fs.existsSync(outputPdfPath) && fs.statSync(outputPdfPath).size > 1000) {
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 300));
      }

      assert.ok(
        fs.existsSync(outputPdfPath),
        "Output document.pdf must be generated by live converter"
      );
      assert.ok(
        fs.statSync(outputPdfPath).size > 1000,
        "Generated PDF must contain valid binary content"
      );
      assert.ok(
        capturedLogChunks.includes("markdown-convert"),
        "Live conversion command must stream execution logs"
      );
      assert.ok(
        fs.existsSync(path.join(projectPath, "conversion.log")),
        "conversion.log file must be created on disk"
      );
    } finally {
      await converterService.stopLiveConversion();
    }
  });

  it("verifies open project constraints strictly", () => {
    const zeroMdFolder = path.join(temporaryRootFolder, "ZeroMdFolder");
    fs.mkdirSync(zeroMdFolder);
    assert.throws(
      () => validateAndOpenProject(zeroMdFolder, testLogger),
      /The project folder contains no markdown files\./
    );

    const multiMdFolder = path.join(temporaryRootFolder, "MultiMdFolder");
    fs.mkdirSync(multiMdFolder);
    fs.writeFileSync(path.join(multiMdFolder, "first.md"), "# One", "utf8");
    fs.writeFileSync(path.join(multiMdFolder, "second.md"), "# Two", "utf8");
    assert.throws(
      () => validateAndOpenProject(multiMdFolder, testLogger),
      /Atarashii only supports one markdown document per project\. To edit multiple markdown files, please create a project folder for each of them\./
    );
  });
});
